# Numpy

**Q1. Create an array of numbers from 10 to 50 with step 5**

In [1]:
import numpy as np

In [6]:
a = np.arange(10,55,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

**Q2**

**Find:**

**min
max
mean**

In [16]:
arr = np.array([5,10,15,20,25])
arr.min()

np.int64(5)

In [17]:
arr.max()

np.int64(25)

In [18]:
arr.mean()

np.float64(15.0)

In [20]:
r = np.arange(1,21)
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
r.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [37]:
r[r%2 == 0]=0
r

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0])

In [58]:
long = np.array([12,56,26,2,17])

res= long[long>20]
res

array([56, 26])

In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = a+b
result

array([5, 7, 9])

In [55]:
arr = np.array([10,50,30,20])
arr.argmax()

np.int64(1)

In [68]:
np.sort(long)[::-1]

array([56, 26, 17, 12,  2])

# Pandas

In [69]:
import pandas as pd

In [100]:
a = pd.DataFrame(
    {
        'Name' : ['a','b','c','a','b'],
        'Age' : [20, 22, 21, 20, 22]
    }
)
a

  Name  Age
0    a   20
1    b   22
2    c   21
3    a   20
4    b   22

In [71]:
a.head(2)

  Name  Age
0    a   20
1    b   22

In [81]:
a[['Age']]

   Age
0   20
1   22
2   21

In [82]:
a[a['Age']>21]

  Name  Age
1    b   22

In [87]:
a['Status'] = 'junior'
a.loc[a['Age']>21, 'Status'] = 'Senior'
a

  Name  Age  Status
0    a   20  junior
1    b   22  Senior
2    c   21  junior

In [92]:
a.sort_values(by = 'Age', ascending= False)

  Name  Age  Status
1    b   22  Senior
2    c   21  junior
0    a   20  junior

In [96]:
a['Age'].mean()

np.float64(21.0)

In [101]:
a['Age'].value_counts()

Age
20    2
22    2
21    1
Name: count, dtype: int64

In [102]:
a.groupby('Age').count()

     Name
Age
20      2
21      1
22      2

In [103]:
df = pd.DataFrame({
    'Dept': ['IT','HR','IT','Finance','HR'],
    'Salary': [50000,40000,60000,45000,42000]
})
df

      Dept  Salary
0       IT   50000
1       HR   40000
2       IT   60000
3  Finance   45000
4       HR   42000

In [106]:
df.groupby('Dept')['Salary'].sum()

Dept
Finance     45000
HR          82000
IT         110000
Name: Salary, dtype: int64

In [108]:
df.groupby('Dept')['Salary'].mean()

Dept
Finance    45000.0
HR         41000.0
IT         55000.0
Name: Salary, dtype: float64