In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name' : ['Ayush', 'Ved', 'Ravi', 'Hemant', 'Aryan', 'Ayush', 'Ravi'],
    'Age'  : [24,45,29,30,55, 36, 22],
    'Salary':[30000,40000,20000,19500,13500, 6734, 3467]
})
df

     Name  Age  Salary
0   Ayush   24   30000
1     Ved   45   40000
2    Ravi   29   20000
3  Hemant   30   19500
4   Aryan   55   13500
5   Ayush   36    6734
6    Ravi   22    3467

In [2]:
df1 = df.groupby('Name')
df1

In [3]:
for x,y in df1:
    
    print(x)
    print(y)

Aryan
    Name  Age  Salary
4  Aryan   55   13500
Ayush
    Name  Age  Salary
0  Ayush   24   30000
5  Ayush   36    6734
Hemant
     Name  Age  Salary
3  Hemant   30   19500
Ravi
   Name  Age  Salary
2  Ravi   29   20000
6  Ravi   22    3467
Ved
  Name  Age  Salary
1  Ved   45   40000

In [ ]:
df2 = df.groupby('Name')['Salary'].max()
df2

Name
Aryan     13500
Ayush     30000
Hemant    19500
Ravi      20000
Ved       40000
Name: Salary, dtype: int64

In [ ]:
df3 = df.groupby('Name')['Salary'].min()
df3

Name
Aryan     13500
Ayush      6734
Hemant    19500
Ravi       3467
Ved       40000
Name: Salary, dtype: int64

In [6]:
df4 = df.groupby('Name')['Salary'].mean()
df4

Name
Aryan     13500.0
Ayush     18367.0
Hemant    19500.0
Ravi      11733.5
Ved       40000.0
Name: Salary, dtype: float64

In [7]:
df5 = df.groupby('Name')['Salary'].count()
df5

Name
Aryan     1
Ayush     2
Hemant    1
Ravi      2
Ved       1
Name: Salary, dtype: int64

In [8]:
df6 = df.groupby('Name').count()
df6

        Age  Salary
Name
Aryan     1       1
Ayush     2       2
Hemant    1       1
Ravi      2       2
Ved       1       1

In [9]:
df7 = df.groupby('Name')['Salary'].sum()
df7

Name
Aryan     13500
Ayush     36734
Hemant    19500
Ravi      23467
Ved       40000
Name: Salary, dtype: int64

In [10]:
df8 = df.groupby('Name')['Salary'].agg(['sum', 'max', 'min', 'mean', 'count'])
df8

          sum    max    min     mean  count
Name
Aryan   13500  13500  13500  13500.0      1
Ayush   36734  30000   6734  18367.0      2
Hemant  19500  19500  19500  19500.0      1
Ravi    23467  20000   3467  11733.5      2
Ved     40000  40000  40000  40000.0      1

In [11]:
df9 = df.groupby('Name')['Salary'].agg(['max'])
df9

          max
Name
Aryan   13500
Ayush   30000
Hemant  19500
Ravi    20000
Ved     40000