# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([i for i in range(1,21)])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
a = np.zeros([5,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
a = np.identity(3)   #only square matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
a = np.eye(3,3)  #flexible (can create non-square)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
a = np.random.rand(10)
a

array([0.03691796, 0.05825862, 0.09986976, 0.26934827, 0.32834303,
       0.26864628, 0.16450659, 0.77412323, 0.39362273, 0.16273005])

In [7]:
a = np.array([4,2,6,9,18,99])
a.shape

(6,)

In [8]:
a.size

6

In [9]:
a.dtype

dtype('int64')

In [10]:
a = a.reshape(2,3)
a

array([[ 4,  2,  6],
       [ 9, 18, 99]])

In [11]:
a.shape

(2, 3)

In [12]:
ayush = np.arange(10,51,2)
ayush

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [13]:
number = np.array([4,85,6,27,6])
number[number > 25] = -1
number

array([ 4, -1,  6, -1,  6])

In [14]:
re = np.arange(1,17).reshape(4,4)
re

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
re.mean()

np.float64(8.5)

In [16]:
np.median(re)

np.float64(8.5)

In [17]:
re.std()

np.float64(4.6097722286464435)

In [18]:
ar1 = np.array([4,6,8,2,1])
ar2 = np.array([9,6,3,7,2])
ar1*ar2

array([36, 36, 24, 14,  2])

In [19]:
a  = np.array([5,9,31,9,8,96,5])

res = np.where(a>30)
res

(array([2, 5]),)

In [20]:
np.sort(a)

array([ 5,  5,  8,  9,  9, 31, 96])

In [21]:
np.unique(a)

array([ 5,  8,  9, 31, 96])

In [22]:
a = np.array([5,6,9])
b = np.array([6,3,7])

np.vstack((a,b))

array([[5, 6, 9],
       [6, 3, 7]])

In [23]:
np.hstack((a,b))

array([5, 6, 9, 6, 3, 7])

# Pandas

In [24]:
import pandas as pd

In [25]:
data = {
    'Name': ['A', 'B', 'C', 'D'],
    'Age': [23, 25, 21, 24],
    'Marks': [85, 90, 78, 88]
}

df = pd.DataFrame(data)
df

  Name  Age  Marks
0    A   23     85
1    B   25     90
2    C   21     78
3    D   24     88

In [26]:
df.head(2)

  Name  Age  Marks
0    A   23     85
1    B   25     90

In [27]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [28]:
df['Name']

0    A
1    B
2    C
3    D
Name: Name, dtype: object

In [29]:
df[df['Age']>22]

  Name  Age  Marks
0    A   23     85
1    B   25     90
3    D   24     88

In [30]:
df['Passed'] = df['Marks']>80
df

  Name  Age  Marks  Passed
0    A   23     85    True
1    B   25     90    True
2    C   21     78   False
3    D   24     88    True

In [31]:
df.sort_values(by = 'Marks', ascending = False)

  Name  Age  Marks  Passed
1    B   25     90    True
3    D   24     88    True
0    A   23     85    True
2    C   21     78   False

In [32]:
df['Marks'].mean()

np.float64(85.25)

In [33]:
df['Marks'].max

<bound method Series.max of 0    85
1    90
2    78
3    88
Name: Marks, dtype: int64>

In [34]:
df.rename(columns={'Marks':'Score'}, inplace = True)

In [35]:
df

  Name  Age  Score  Passed
0    A   23     85    True
1    B   25     90    True
2    C   21     78   False
3    D   24     88    True