# 1. Dataframe

In [1]:
import pandas as pd

df = pd.DataFrame([11,22,33],columns=['Num'])

df

   Num
0   11
1   22
2   33

In [2]:
StudentDetails = {
                "Name": ["Ayush", "Manish", "Ved", "Hemant"],
                "Age" : [23, 22, 45, 24],
                "Marks":[85.63, 99.99, 87.63, 84.56] 
                 }

Result = pd.DataFrame(StudentDetails)
print(Result)

     Name  Age  Marks
0   Ayush   23  85.63
1  Manish   22  99.99
2     Ved   45  87.63
3  Hemant   24  84.56

***Type Check***

In [3]:
print(type(Result))

<class 'pandas.core.frame.DataFrame'>

# 2. Basic DataFrame Understanding

**. I want top row of data**

In [4]:
Employee = {
                "Name" : ["Ramesh", "Suresh", "Rahu", "Kaju", "Umesh", "Rohan","Suresh", "Ravi"],
                "Emp_id":[101, 102, 103, 104, 105, 106, 107, 108],
                "Salary":[85000, 69310, 48612, 45962, 75961, 45861, 32569, 65897]
           }
df = pd.DataFrame(Employee)

print(df.head(2))   #bydefault it takes top 5 rows

     Name  Emp_id  Salary
0  Ramesh     101   85000
1  Suresh     102   69310

**. I want bottom row of data**

In [5]:
Employee = {
                "Name" : ["Ramesh", "Suresh", "Rahu", "Kaju", "Umesh", "Rohan","Suresh", "Ravi"],
                "Emp_id":[101, 102, 103, 104, 105, 106, 107, 108],
                "Salary":[85000, 69310, 48612, 45962, 75961, 45861, 32569, 65897]
           }
df = pd.DataFrame(Employee)

print(df.tail(3))   #bydefault it takes bottom 5 rows

     Name  Emp_id  Salary
5   Rohan     106   45861
6  Suresh     107   32569
7    Ravi     108   65897

In [6]:
df.shape

(8, 3)

In [7]:
df.columns

Index(['Name', 'Emp_id', 'Salary'], dtype='object')

**. Rename Column Name**

In [8]:
df.rename(columns={'Salary': 'Payment'})

     Name  Emp_id  Payment
0  Ramesh     101    85000
1  Suresh     102    69310
2    Rahu     103    48612
3    Kaju     104    45962
4   Umesh     105    75961
5   Rohan     106    45861
6  Suresh     107    32569
7    Ravi     108    65897

In [9]:
df

     Name  Emp_id  Salary
0  Ramesh     101   85000
1  Suresh     102   69310
2    Rahu     103   48612
3    Kaju     104   45962
4   Umesh     105   75961
5   Rohan     106   45861
6  Suresh     107   32569
7    Ravi     108   65897

In [10]:
df.rename(columns={'Salary': 'Payment'}, inplace  = True)

In [11]:
df

     Name  Emp_id  Payment
0  Ramesh     101    85000
1  Suresh     102    69310
2    Rahu     103    48612
3    Kaju     104    45962
4   Umesh     105    75961
5   Rohan     106    45861
6  Suresh     107    32569
7    Ravi     108    65897

In [12]:
df1 = df.rename(columns={'Salary': 'Payment'})

In [13]:
df1

     Name  Emp_id  Payment
0  Ramesh     101    85000
1  Suresh     102    69310
2    Rahu     103    48612
3    Kaju     104    45962
4   Umesh     105    75961
5   Rohan     106    45861
6  Suresh     107    32569
7    Ravi     108    65897

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     8 non-null      object
 1   Emp_id   8 non-null      int64
 2   Payment  8 non-null      int64
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes

In [15]:
df.describe()

          Emp_id       Payment
count    8.00000      8.000000
mean   104.50000  58646.500000
std      2.44949  17990.757953
min    101.00000  32569.000000
25%    102.75000  45936.750000
50%    104.50000  57254.500000
75%    106.25000  70972.750000
max    108.00000  85000.000000

# 3. Save and Load Data from CSV (comma Seperated Value)

In [18]:
# Export Data

df.to_csv('Employee_Data.csv',index=False)  #if index = True then show index Value in data

In [24]:
#Import Data

ld = pd.read_csv('Employee_Data.csv')

print(ld)

     Name  Emp_id  Payment
0  Ramesh     101    85000
1  Suresh     102    69310
2    Rahu     103    48612
3    Kaju     104    45962
4   Umesh     105    75961
5   Rohan     106    45861
6  Suresh     107    32569
7    Ravi     108    65897
8  Vikram     109    56987