Create a pandas DataFrame with columns: Name, Age, City, Salary.

In [1]:
import pandas as pd

a = pd.DataFrame({
                    'Name'  : ['Ayush', 'ved', 'ravi', 'raju', 'piyush', 'hemant', 'ashutosh'],
                    'Age'   :  [21, 56,45,26,78,38,53],
                    'city'  : ['Patna', 'Goa', 'rachi', 'gwalior', 'kouymbtor', 'delhi', 'noida'],
                    'salary': [3400.90, 7856.78, 5638.90, 56.90, 2458.40, 563.90, 1464.20]
})

a

       Name  Age       city   salary
0     Ayush   21      Patna  3400.90
1       ved   56        Goa  7856.78
2      ravi   45      rachi  5638.90
3      raju   26    gwalior    56.90
4    piyush   78  kouymbtor  2458.40
5    hemant   38      delhi   563.90
6  ashutosh   53      noida  1464.20

In [2]:
a.columns

Index(['Name', 'Age', 'city', 'salary'], dtype='object')

In [3]:
a.head(5)

     Name  Age       city   salary
0   Ayush   21      Patna  3400.90
1     ved   56        Goa  7856.78
2    ravi   45      rachi  5638.90
3    raju   26    gwalior    56.90
4  piyush   78  kouymbtor  2458.40

In [4]:
a.tail(3)

       Name  Age       city  salary
4    piyush   78  kouymbtor  2458.4
5    hemant   38      delhi   563.9
6  ashutosh   53      noida  1464.2

In [5]:
a.dtypes

Name       object
Age         int64
city       object
salary    float64
dtype: object

In [6]:
a[['Name','Age']]

       Name  Age
0     Ayush   21
1       ved   56
2      ravi   45
3      raju   26
4    piyush   78
5    hemant   38
6  ashutosh   53

In [7]:
import pandas as pd

d = pd.read_excel(
    r"C:\Users\ayush\Downloads\Practice_Analysis.xlsx",
    sheet_name='Sep PJP',
    header = 1
    
)

C:\Users\ayush\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\ayush\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [8]:
df = pd.DataFrame(d)

In [9]:
df

         Date        Day          FULL NAME      PLACE  AMOUNT
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455
15        NaT        NaN                NaN  Total   =  376732

In [10]:
df = df[:-1]
df

         Date        Day          FULL NAME      PLACE  AMOUNT
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455

In [11]:
df.loc[3:6,["FULL NAME","AMOUNT"]]

           FULL NAME  AMOUNT
3           RAVI RAM     265
4       MANISH SINGH    5465
5           GOLU RAJ    5000
6  SARVAN SINGHANIYA   50546

In [12]:
df.loc[3:6,"FULL NAME":"AMOUNT"]

           FULL NAME      PLACE  AMOUNT
3           RAVI RAM  SAHABGANJ     265
4       MANISH SINGH   week off    5465
5           GOLU RAJ   SAIDUPUR    5000
6  SARVAN SINGHANIYA   CHAHNIYA   50546

In [13]:
p =df.loc[:, 'FULL NAME']
p

0      AYUSH SRIVASTAVA
1          PIYUSH KUMAR
2            RAJU GUPTA
3              RAVI RAM
4          MANISH SINGH
5              GOLU RAJ
6     SARVAN SINGHANIYA
7          ANKUR MAURYA
8          VIKRAM KUMAR
9           VIKRANT LAL
10       RAMESH PASWAAN
11          VED VISHNOI
12        HEMANT PANDEY
13          ARYAN DUBEY
14      ASHUTOSH TIWARI
Name: FULL NAME, dtype: object

In [14]:
df.columns

Index(['Date', 'Day', 'FULL NAME', 'PLACE', 'AMOUNT'], dtype='object')

In [15]:
df.head(5)

        Date        Day         FULL NAME      PLACE  AMOUNT
0 2026-04-01  WEDNESDAY  AYUSH SRIVASTAVA  SAKALDIHA    5000
1 2026-04-02   THURSDAY      PIYUSH KUMAR      LEAVE    6848
2 2026-04-03     FRIDAY        RAJU GUPTA   SAIDRAJA   64973
3 2026-04-04   SATURDAY          RAVI RAM  SAHABGANJ     265
4 2026-04-05     SUNDAY      MANISH SINGH   week off    5465

In [16]:
df['AMOUNT'].sum()

np.int64(376732)

In [17]:
df[df['PLACE'] == 'CHAHNIYA']

         Date        Day          FULL NAME     PLACE  AMOUNT
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA  CHAHNIYA   50546
13 2026-04-14    TUESDAY        ARYAN DUBEY  CHAHNIYA       1
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI  CHAHNIYA   84455

In [18]:
df

         Date        Day          FULL NAME      PLACE  AMOUNT
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455

In [19]:
df.iloc[0,3]

'SAKALDIHA'

In [20]:
df.iloc[1:3, 1:4]

        Day     FULL NAME     PLACE
1  THURSDAY  PIYUSH KUMAR     LEAVE
2    FRIDAY    RAJU GUPTA  SAIDRAJA

In [21]:
df

         Date        Day          FULL NAME      PLACE  AMOUNT
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455

In [22]:
df['Bonus'] = [800, 900, 864, 697, 4587, 7569, 2486, 4789, 1248,6845, 14896, 14759, 2586, 3657, 4896]

C:\Users\ayush\AppData\Local\Temp\ipykernel_16648\719529215.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Bonus'] = [800, 900, 864, 697, 4587, 7569, 2486, 4789, 1248,6845, 14896, 14759, 2586, 3657, 4896]

In [23]:
df['Total Amount After Bonus'] = df['AMOUNT']*df['Bonus']

C:\Users\ayush\AppData\Local\Temp\ipykernel_16648\3343231212.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Total Amount After Bonus'] = df['AMOUNT']*df['Bonus']

In [24]:
df

,Date,Day,FULL NAME,PLACE,AMOUNT,Bonus,Total Amount After Bonus
0,2026-04-01,WEDNESDAY,AYUSH SRIVASTAVA,SAKALDIHA,5000,800,4000000
1,2026-04-02,THURSDAY,PIYUSH KUMAR,LEAVE,6848,900,6163200
2,2026-04-03,FRIDAY,RAJU GUPTA,SAIDRAJA,64973,864,56136672
3,2026-04-04,SATURDAY,RAVI RAM,SAHABGANJ,265,697,184705
4,2026-04-05,SUNDAY,MANISH SINGH,week off,5465,4587,25067955
5,2026-04-06,MONDAY,GOLU RAJ,SAIDUPUR,5000,7569,37845000
6,2026-04-07,TUESDAY,SARVAN SINGHANIYA,CHAHNIYA,50546,2486,125657356
7,2026-04-08,WEDNESDAY,ANKUR MAURYA,DHANAPUR,5148,4789,24653772
8,2026-04-09,THURSDAY,VIKRAM KUMAR,KAMALPUR,84454,1248,105398592
9,2026-04-10,FRIDAY,VIKRANT LAL,CHAKIA,51454,6845,352202630
10,2026-04-11,SATURDAY,RAMESH PASWAAN,BABURI,5154,14896,76773984
11,2026-04-12,SUNDAY,VED VISHNOI,week off,5485,14759,80953115
12,2026-04-13,MONDAY,HEMANT PANDEY,SAHABGANJ,2484,2586,6423624
13,2026-04-14,TUESDAY,ARYAN DUBEY,CHAHNIYA,1,3657,3657
14,2026-04-15,WEDNESDAY,ASHUTOSH TIWARI,CHAHNIYA,84455,4896,413491680

In [25]:
df.rename(columns={'Total Amount After Bonus' : 'Total Amount'}, inplace = True)

df

C:\Users\ayush\AppData\Local\Temp\ipykernel_16648\3498702770.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Total Amount After Bonus' : 'Total Amount'}, inplace = True)

,Date,Day,FULL NAME,PLACE,AMOUNT,Bonus,Total Amount
0,2026-04-01,WEDNESDAY,AYUSH SRIVASTAVA,SAKALDIHA,5000,800,4000000
1,2026-04-02,THURSDAY,PIYUSH KUMAR,LEAVE,6848,900,6163200
2,2026-04-03,FRIDAY,RAJU GUPTA,SAIDRAJA,64973,864,56136672
3,2026-04-04,SATURDAY,RAVI RAM,SAHABGANJ,265,697,184705
4,2026-04-05,SUNDAY,MANISH SINGH,week off,5465,4587,25067955
5,2026-04-06,MONDAY,GOLU RAJ,SAIDUPUR,5000,7569,37845000
6,2026-04-07,TUESDAY,SARVAN SINGHANIYA,CHAHNIYA,50546,2486,125657356
7,2026-04-08,WEDNESDAY,ANKUR MAURYA,DHANAPUR,5148,4789,24653772
8,2026-04-09,THURSDAY,VIKRAM KUMAR,KAMALPUR,84454,1248,105398592
9,2026-04-10,FRIDAY,VIKRANT LAL,CHAKIA,51454,6845,352202630
10,2026-04-11,SATURDAY,RAMESH PASWAAN,BABURI,5154,14896,76773984
11,2026-04-12,SUNDAY,VED VISHNOI,week off,5485,14759,80953115
12,2026-04-13,MONDAY,HEMANT PANDEY,SAHABGANJ,2484,2586,6423624
13,2026-04-14,TUESDAY,ARYAN DUBEY,CHAHNIYA,1,3657,3657
14,2026-04-15,WEDNESDAY,ASHUTOSH TIWARI,CHAHNIYA,84455,4896,413491680

In [26]:
df.drop('Total Amount', axis = 1, inplace = True)

C:\Users\ayush\AppData\Local\Temp\ipykernel_16648\2669763105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Total Amount', axis = 1, inplace = True)

In [27]:
df

         Date        Day          FULL NAME      PLACE  AMOUNT  Bonus
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000    800
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848    900
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973    864
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265    697
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465   4587
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000   7569
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546   2486
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148   4789
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454   1248
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454   6845
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154  14896
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485  14759
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484   2586
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1   3657
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455   4896

In [28]:
df.set_index('Date', inplace=True)
print(df)

                  Day          FULL NAME      PLACE  AMOUNT  Bonus
Date
2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000    800
2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848    900
2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973    864
2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265    697
2026-04-05     SUNDAY       MANISH SINGH   week off    5465   4587
2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000   7569
2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546   2486
2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148   4789
2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454   1248
2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454   6845
2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154  14896
2026-04-12     SUNDAY        VED VISHNOI   week off    5485  14759
2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484   2586
2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1   3657
2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455   4896

In [29]:
df.reset_index(inplace=True)

df

         Date        Day          FULL NAME      PLACE  AMOUNT  Bonus
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000    800
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848    900
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973    864
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265    697
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465   4587
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000   7569
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546   2486
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148   4789
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454   1248
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454   6845
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154  14896
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485  14759
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484   2586
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1   3657
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455   4896

In [30]:
# df.drop('Bonus', axis = 1, inplace = True)

In [31]:
df

         Date        Day          FULL NAME      PLACE  AMOUNT  Bonus
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000    800
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848    900
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973    864
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265    697
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465   4587
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000   7569
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546   2486
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148   4789
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454   1248
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454   6845
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154  14896
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485  14759
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484   2586
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1   3657
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455   4896

In [32]:
p = df[df['AMOUNT']>50000]
p

         Date        Day          FULL NAME     PLACE  AMOUNT  Bonus
2  2026-04-03     FRIDAY         RAJU GUPTA  SAIDRAJA   64973    864
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA  CHAHNIYA   50546   2486
8  2026-04-09   THURSDAY       VIKRAM KUMAR  KAMALPUR   84454   1248
9  2026-04-10     FRIDAY        VIKRANT LAL    CHAKIA   51454   6845
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI  CHAHNIYA   84455   4896

In [33]:
city = df[df['PLACE'] == 'CHAHNIYA']
city

         Date        Day          FULL NAME     PLACE  AMOUNT  Bonus
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA  CHAHNIYA   50546   2486
13 2026-04-14    TUESDAY        ARYAN DUBEY  CHAHNIYA       1   3657
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI  CHAHNIYA   84455   4896

In [34]:
aa = df[df['AMOUNT'].between(5000,10000)]

aa

         Date        Day         FULL NAME      PLACE  AMOUNT  Bonus
0  2026-04-01  WEDNESDAY  AYUSH SRIVASTAVA  SAKALDIHA    5000    800
1  2026-04-02   THURSDAY      PIYUSH KUMAR      LEAVE    6848    900
4  2026-04-05     SUNDAY      MANISH SINGH   week off    5465   4587
5  2026-04-06     MONDAY          GOLU RAJ   SAIDUPUR    5000   7569
7  2026-04-08  WEDNESDAY      ANKUR MAURYA   DHANAPUR    5148   4789
10 2026-04-11   SATURDAY    RAMESH PASWAAN     BABURI    5154  14896
11 2026-04-12     SUNDAY       VED VISHNOI   week off    5485  14759

In [35]:
df.sort_values('AMOUNT', ascending=True)

         Date        Day          FULL NAME      PLACE  AMOUNT  Bonus
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1   3657
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265    697
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484   2586
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000    800
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000   7569
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148   4789
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154  14896
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465   4587
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485  14759
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848    900
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546   2486
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454   6845
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973    864
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454   1248
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455   4896

In [36]:
df.sort_values(['Date', 'AMOUNT'])

         Date        Day          FULL NAME      PLACE  AMOUNT  Bonus
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000    800
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848    900
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973    864
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265    697
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465   4587
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000   7569
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546   2486
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148   4789
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454   1248
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454   6845
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154  14896
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485  14759
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484   2586
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1   3657
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455   4896

In [37]:
df.sort_values(['Date', 'AMOUNT'], ascending = [True, False])

         Date        Day          FULL NAME      PLACE  AMOUNT  Bonus
0  2026-04-01  WEDNESDAY   AYUSH SRIVASTAVA  SAKALDIHA    5000    800
1  2026-04-02   THURSDAY       PIYUSH KUMAR      LEAVE    6848    900
2  2026-04-03     FRIDAY         RAJU GUPTA   SAIDRAJA   64973    864
3  2026-04-04   SATURDAY           RAVI RAM  SAHABGANJ     265    697
4  2026-04-05     SUNDAY       MANISH SINGH   week off    5465   4587
5  2026-04-06     MONDAY           GOLU RAJ   SAIDUPUR    5000   7569
6  2026-04-07    TUESDAY  SARVAN SINGHANIYA   CHAHNIYA   50546   2486
7  2026-04-08  WEDNESDAY       ANKUR MAURYA   DHANAPUR    5148   4789
8  2026-04-09   THURSDAY       VIKRAM KUMAR   KAMALPUR   84454   1248
9  2026-04-10     FRIDAY        VIKRANT LAL     CHAKIA   51454   6845
10 2026-04-11   SATURDAY     RAMESH PASWAAN     BABURI    5154  14896
11 2026-04-12     SUNDAY        VED VISHNOI   week off    5485  14759
12 2026-04-13     MONDAY      HEMANT PANDEY  SAHABGANJ    2484   2586
13 2026-04-14    TUESDAY        ARYAN DUBEY   CHAHNIYA       1   3657
14 2026-04-15  WEDNESDAY    ASHUTOSH TIWARI   CHAHNIYA   84455   4896