# 1. Dataframe

In [1]:
import pandas as pd

df = pd.DataFrame([11,22,33],columns=['Num'])

df

   Num
0   11
1   22
2   33

In [2]:
StudentDetails = {
                "Name": ["Ayush", "Manish", "Ved", "Hemant"],
                "Age" : [23, 22, 45, 24],
                "Marks":[85.63, 99.99, 87.63, 84.56],
                 }

Result = pd.DataFrame(StudentDetails)
print(Result)

     Name  Age  Marks
0   Ayush   23  85.63
1  Manish   22  99.99
2     Ved   45  87.63
3  Hemant   24  84.56

***Type Check***

In [3]:
print(type(Result))

<class 'pandas.core.frame.DataFrame'>

# 2. Basic DataFrame Understanding

**. I want top row of data**

In [4]:
Employee = {
                "Name" : ["Ramesh", "Suresh", "Rahu", "Kaju", "Umesh", "Rohan","Suresh", "Ravi"],
                "Emp_id":[101, 102, 103, 104, 105, 106, 107, 108],
                "Salary":[85000, 69310, 48612, 45962, 75961, 45861, 32569, 65897],
                "Age" : [25, 36, 86, 46, 30, 40, 55, 60]
           }
df = pd.DataFrame(Employee)

print(df.head(2))   #bydefault it takes top 5 rows

     Name  Emp_id  Salary  Age
0  Ramesh     101   85000   25
1  Suresh     102   69310   36

**. I want bottom row of data**

In [5]:
Employee = {
                "Name" : ["Ramesh", "Suresh", "Rahu", "Kaju", "Umesh", "Rohan","Suresh", "Ravi"],
                "Emp_id":[101, 102, 103, 104, 105, 106, 107, 108],
                "Salary":[85000, 69310, 48612, 45962, 75961, 45861, 32569, 65897],
                "Age" : [25, 36, 86, 46, 30, 40, 55, 60]
           }
df = pd.DataFrame(Employee)

print(df.tail(3))   #bydefault it takes bottom 5 rows

     Name  Emp_id  Salary  Age
5   Rohan     106   45861   40
6  Suresh     107   32569   55
7    Ravi     108   65897   60

In [6]:
df.shape

(8, 4)

In [7]:
df.columns

Index(['Name', 'Emp_id', 'Salary', 'Age'], dtype='object')

**. Rename Column Name**

In [8]:
df.rename(columns={'Salary': 'Payment'})

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36
2    Rahu     103    48612   86
3    Kaju     104    45962   46
4   Umesh     105    75961   30
5   Rohan     106    45861   40
6  Suresh     107    32569   55
7    Ravi     108    65897   60

In [9]:
df

     Name  Emp_id  Salary  Age
0  Ramesh     101   85000   25
1  Suresh     102   69310   36
2    Rahu     103   48612   86
3    Kaju     104   45962   46
4   Umesh     105   75961   30
5   Rohan     106   45861   40
6  Suresh     107   32569   55
7    Ravi     108   65897   60

In [10]:
df.rename(columns={'Salary': 'Payment'}, inplace  = True)

In [11]:
df

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36
2    Rahu     103    48612   86
3    Kaju     104    45962   46
4   Umesh     105    75961   30
5   Rohan     106    45861   40
6  Suresh     107    32569   55
7    Ravi     108    65897   60

In [12]:
df1 = df.rename(columns={'Salary':'Payment'})

In [13]:
df1

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36
2    Rahu     103    48612   86
3    Kaju     104    45962   46
4   Umesh     105    75961   30
5   Rohan     106    45861   40
6  Suresh     107    32569   55
7    Ravi     108    65897   60

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     8 non-null      object
 1   Emp_id   8 non-null      int64
 2   Payment  8 non-null      int64
 3   Age      8 non-null      int64
dtypes: int64(3), object(1)
memory usage: 388.0+ bytes

In [15]:
df.describe()

          Emp_id       Payment        Age
count    8.00000      8.000000   8.000000
mean   104.50000  58646.500000  47.250000
std      2.44949  17990.757953  19.630516
min    101.00000  32569.000000  25.000000
25%    102.75000  45936.750000  34.500000
50%    104.50000  57254.500000  43.000000
75%    106.25000  70972.750000  56.250000
max    108.00000  85000.000000  86.000000

# 3. Save and Load Data from CSV (comma Seperated Value)

In [16]:
# Export Data

df.to_csv('Employee_Data.csv',index=False)  #if index = True then show index Value in data

In [17]:
#Import Data

ld = pd.read_csv('Employee_Data.csv')

print(ld)

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36
2    Rahu     103    48612   86
3    Kaju     104    45962   46
4   Umesh     105    75961   30
5   Rohan     106    45861   40
6  Suresh     107    32569   55
7    Ravi     108    65897   60

# 4. Rows & Column - Selection

In [18]:
#Select Single Column

df[['Name']]

     Name
0  Ramesh
1  Suresh
2    Rahu
3    Kaju
4   Umesh
5   Rohan
6  Suresh
7    Ravi

In [19]:
#Select Multiple Columns

df[['Name', 'Payment']]

     Name  Payment
0  Ramesh    85000
1  Suresh    69310
2    Rahu    48612
3    Kaju    45962
4   Umesh    75961
5   Rohan    45861
6  Suresh    32569
7    Ravi    65897

In [20]:
# Select Single Row
#loc = label Based index
df.loc[df.Name == 'Umesh']

    Name  Emp_id  Payment  Age
4  Umesh     105    75961   30

In [21]:
df.loc[(df.Name=='Kaju') & (df.Payment>=40000)]

   Name  Emp_id  Payment  Age
3  Kaju     104    45962   46

In [22]:
df.loc[df['Payment'] == df['Payment'].max()]

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25

In [23]:
#iloc = index-Value Based

df.iloc

In [24]:
df.iloc[0:2]

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36

In [25]:
df.iloc[:]

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36
2    Rahu     103    48612   86
3    Kaju     104    45962   46
4   Umesh     105    75961   30
5   Rohan     106    45861   40
6  Suresh     107    32569   55
7    Ravi     108    65897   60

**Difference Of loc And iloc**

In [26]:
df.loc[0:2]

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36
2    Rahu     103    48612   86

In [27]:
df.iloc[0:2] #[start:stop:step]

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36

# 5. Filter DataFrame

In [28]:
df

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36
2    Rahu     103    48612   86
3    Kaju     104    45962   46
4   Umesh     105    75961   30
5   Rohan     106    45861   40
6  Suresh     107    32569   55
7    Ravi     108    65897   60

In [29]:
df[df['Payment'] > 65000]

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36
4   Umesh     105    75961   30
7    Ravi     108    65897   60

In [30]:
df[(df['Age']>55) & (df['Payment']>40000) ]

   Name  Emp_id  Payment  Age
2  Rahu     103    48612   86
7  Ravi     108    65897   60

In [31]:
df.where(df['Age']>55, other = 'Not Eligible')

           Name        Emp_id       Payment           Age
0  Not Eligible  Not Eligible  Not Eligible  Not Eligible
1  Not Eligible  Not Eligible  Not Eligible  Not Eligible
2          Rahu           103         48612            86
3  Not Eligible  Not Eligible  Not Eligible  Not Eligible
4  Not Eligible  Not Eligible  Not Eligible  Not Eligible
5  Not Eligible  Not Eligible  Not Eligible  Not Eligible
6  Not Eligible  Not Eligible  Not Eligible  Not Eligible
7          Ravi           108         65897            60

# 6. Rows and Columns - Operation(Add, Update, Delete, sort)

In [32]:
df

     Name  Emp_id  Payment  Age
0  Ramesh     101    85000   25
1  Suresh     102    69310   36
2    Rahu     103    48612   86
3    Kaju     104    45962   46
4   Umesh     105    75961   30
5   Rohan     106    45861   40
6  Suresh     107    32569   55
7    Ravi     108    65897   60

**. Add New Column**

In [33]:
df['Job-Role'] = ['Backend-Developer', 'Tester', 'Production', 'Marketing', 'HR', 'Analysis', 'Manager', 'frontent-Developer']

In [34]:
df

     Name  Emp_id  Payment  Age            Job-Role
0  Ramesh     101    85000   25   Backend-Developer
1  Suresh     102    69310   36              Tester
2    Rahu     103    48612   86          Production
3    Kaju     104    45962   46           Marketing
4   Umesh     105    75961   30                  HR
5   Rohan     106    45861   40            Analysis
6  Suresh     107    32569   55             Manager
7    Ravi     108    65897   60  frontent-Developer

In [35]:
df['Bonus'] = df['Payment'] * 0.2

In [36]:
df

     Name  Emp_id  Payment  Age            Job-Role    Bonus
0  Ramesh     101    85000   25   Backend-Developer  17000.0
1  Suresh     102    69310   36              Tester  13862.0
2    Rahu     103    48612   86          Production   9722.4
3    Kaju     104    45962   46           Marketing   9192.4
4   Umesh     105    75961   30                  HR  15192.2
5   Rohan     106    45861   40            Analysis   9172.2
6  Suresh     107    32569   55             Manager   6513.8
7    Ravi     108    65897   60  frontent-Developer  13179.4

**. Add New Row**

In [37]:
df.loc[len(df)] = ['Vikram', 109, 12503, 23, 'AI/ML Devp', 900]

In [38]:
df

     Name  Emp_id  Payment  Age            Job-Role    Bonus
0  Ramesh     101    85000   25   Backend-Developer  17000.0
1  Suresh     102    69310   36              Tester  13862.0
2    Rahu     103    48612   86          Production   9722.4
3    Kaju     104    45962   46           Marketing   9192.4
4   Umesh     105    75961   30                  HR  15192.2
5   Rohan     106    45861   40            Analysis   9172.2
6  Suresh     107    32569   55             Manager   6513.8
7    Ravi     108    65897   60  frontent-Developer  13179.4
8  Vikram     109    12503   23          AI/ML Devp    900.0

In [39]:
len(df)

9

**. Update Value Using index Name**

In [40]:
df.loc[8, 'Payment'] = 90267
df

     Name  Emp_id  Payment  Age            Job-Role    Bonus
0  Ramesh     101    85000   25   Backend-Developer  17000.0
1  Suresh     102    69310   36              Tester  13862.0
2    Rahu     103    48612   86          Production   9722.4
3    Kaju     104    45962   46           Marketing   9192.4
4   Umesh     105    75961   30                  HR  15192.2
5   Rohan     106    45861   40            Analysis   9172.2
6  Suresh     107    32569   55             Manager   6513.8
7    Ravi     108    65897   60  frontent-Developer  13179.4
8  Vikram     109    90267   23          AI/ML Devp    900.0

**. Update Value Using index value**

In [41]:
df.loc[df.Name == 'Rohan', 'Payment'] = 46000
df

     Name  Emp_id  Payment  Age            Job-Role    Bonus
0  Ramesh     101    85000   25   Backend-Developer  17000.0
1  Suresh     102    69310   36              Tester  13862.0
2    Rahu     103    48612   86          Production   9722.4
3    Kaju     104    45962   46           Marketing   9192.4
4   Umesh     105    75961   30                  HR  15192.2
5   Rohan     106    46000   40            Analysis   9172.2
6  Suresh     107    32569   55             Manager   6513.8
7    Ravi     108    65897   60  frontent-Developer  13179.4
8  Vikram     109    90267   23          AI/ML Devp    900.0

**. Delete Row & Column Values**

In [42]:
df.drop(df[df.Name == 'Vikram'].index, inplace = True) #Drop row, axis=0
df

     Name  Emp_id  Payment  Age            Job-Role    Bonus
0  Ramesh     101    85000   25   Backend-Developer  17000.0
1  Suresh     102    69310   36              Tester  13862.0
2    Rahu     103    48612   86          Production   9722.4
3    Kaju     104    45962   46           Marketing   9192.4
4   Umesh     105    75961   30                  HR  15192.2
5   Rohan     106    46000   40            Analysis   9172.2
6  Suresh     107    32569   55             Manager   6513.8
7    Ravi     108    65897   60  frontent-Developer  13179.4

In [43]:
df.drop(5, axis=0) #Drop Row Using Index

     Name  Emp_id  Payment  Age            Job-Role    Bonus
0  Ramesh     101    85000   25   Backend-Developer  17000.0
1  Suresh     102    69310   36              Tester  13862.0
2    Rahu     103    48612   86          Production   9722.4
3    Kaju     104    45962   46           Marketing   9192.4
4   Umesh     105    75961   30                  HR  15192.2
6  Suresh     107    32569   55             Manager   6513.8
7    Ravi     108    65897   60  frontent-Developer  13179.4

In [44]:
df.drop('Bonus', axis =1, inplace = True)
df

     Name  Emp_id  Payment  Age            Job-Role
0  Ramesh     101    85000   25   Backend-Developer
1  Suresh     102    69310   36              Tester
2    Rahu     103    48612   86          Production
3    Kaju     104    45962   46           Marketing
4   Umesh     105    75961   30                  HR
5   Rohan     106    46000   40            Analysis
6  Suresh     107    32569   55             Manager
7    Ravi     108    65897   60  frontent-Developer

In [45]:
# df.drop(['Age', 'Payment'], axis=1)  #Delete multiple columns

In [46]:
df

     Name  Emp_id  Payment  Age            Job-Role
0  Ramesh     101    85000   25   Backend-Developer
1  Suresh     102    69310   36              Tester
2    Rahu     103    48612   86          Production
3    Kaju     104    45962   46           Marketing
4   Umesh     105    75961   30                  HR
5   Rohan     106    46000   40            Analysis
6  Suresh     107    32569   55             Manager
7    Ravi     108    65897   60  frontent-Developer

**. Sort**

In [47]:
df.sort_values('Age')  #Ascending Order

     Name  Emp_id  Payment  Age            Job-Role
0  Ramesh     101    85000   25   Backend-Developer
4   Umesh     105    75961   30                  HR
1  Suresh     102    69310   36              Tester
5   Rohan     106    46000   40            Analysis
3    Kaju     104    45962   46           Marketing
6  Suresh     107    32569   55             Manager
7    Ravi     108    65897   60  frontent-Developer
2    Rahu     103    48612   86          Production

In [48]:
df.sort_values('Age', ascending=False)  #Descending Order

     Name  Emp_id  Payment  Age            Job-Role
2    Rahu     103    48612   86          Production
7    Ravi     108    65897   60  frontent-Developer
6  Suresh     107    32569   55             Manager
3    Kaju     104    45962   46           Marketing
5   Rohan     106    46000   40            Analysis
1  Suresh     102    69310   36              Tester
4   Umesh     105    75961   30                  HR
0  Ramesh     101    85000   25   Backend-Developer

# 7. Working With Date Value

In [49]:
df['DOJ'] = ['2002-07-13', '2026-09-01', '2000-09-01',
             '1999-04-09', '2000-01-01', '2007-12-12',
             '2016-03-09', '2019-09-06']
df

     Name  Emp_id  Payment  Age            Job-Role         DOJ
0  Ramesh     101    85000   25   Backend-Developer  2002-07-13
1  Suresh     102    69310   36              Tester  2026-09-01
2    Rahu     103    48612   86          Production  2000-09-01
3    Kaju     104    45962   46           Marketing  1999-04-09
4   Umesh     105    75961   30                  HR  2000-01-01
5   Rohan     106    46000   40            Analysis  2007-12-12
6  Suresh     107    32569   55             Manager  2016-03-09
7    Ravi     108    65897   60  frontent-Developer  2019-09-06

In [50]:
df['DOJ'].dtype

dtype('O')

In [51]:
df['DOJ'] = pd.to_datetime(df['DOJ'])
df['DOJ'].dtype

dtype('<M8[ns]')

In [52]:
df['DOJ'].dt.year
df['DOJ'].dt.month
df['Day'] = df['DOJ'].dt.day
df['Day_Name']=df['DOJ'].dt.day_name()

In [53]:
df

     Name  Emp_id  Payment  Age            Job-Role        DOJ  Day   Day_Name
0  Ramesh     101    85000   25   Backend-Developer 2002-07-13   13   Saturday
1  Suresh     102    69310   36              Tester 2026-09-01    1    Tuesday
2    Rahu     103    48612   86          Production 2000-09-01    1     Friday
3    Kaju     104    45962   46           Marketing 1999-04-09    9     Friday
4   Umesh     105    75961   30                  HR 2000-01-01    1   Saturday
5   Rohan     106    46000   40            Analysis 2007-12-12   12  Wednesday
6  Suresh     107    32569   55             Manager 2016-03-09    9  Wednesday
7    Ravi     108    65897   60  frontent-Developer 2019-09-06    6     Friday

# 8. Handling Missing Value

In [54]:
df

     Name  Emp_id  Payment  Age            Job-Role        DOJ  Day   Day_Name
0  Ramesh     101    85000   25   Backend-Developer 2002-07-13   13   Saturday
1  Suresh     102    69310   36              Tester 2026-09-01    1    Tuesday
2    Rahu     103    48612   86          Production 2000-09-01    1     Friday
3    Kaju     104    45962   46           Marketing 1999-04-09    9     Friday
4   Umesh     105    75961   30                  HR 2000-01-01    1   Saturday
5   Rohan     106    46000   40            Analysis 2007-12-12   12  Wednesday
6  Suresh     107    32569   55             Manager 2016-03-09    9  Wednesday
7    Ravi     108    65897   60  frontent-Developer 2019-09-06    6     Friday

In [55]:
df.isnull()

    Name  Emp_id  Payment    Age  Job-Role    DOJ    Day  Day_Name
0  False   False    False  False     False  False  False     False
1  False   False    False  False     False  False  False     False
2  False   False    False  False     False  False  False     False
3  False   False    False  False     False  False  False     False
4  False   False    False  False     False  False  False     False
5  False   False    False  False     False  False  False     False
6  False   False    False  False     False  False  False     False
7  False   False    False  False     False  False  False     False

In [56]:
import numpy as np
df.loc[df.Name== 'Kaju', 'Payment']=np.nan
df

     Name  Emp_id  Payment  Age            Job-Role        DOJ  Day   Day_Name
0  Ramesh     101  85000.0   25   Backend-Developer 2002-07-13   13   Saturday
1  Suresh     102  69310.0   36              Tester 2026-09-01    1    Tuesday
2    Rahu     103  48612.0   86          Production 2000-09-01    1     Friday
3    Kaju     104      NaN   46           Marketing 1999-04-09    9     Friday
4   Umesh     105  75961.0   30                  HR 2000-01-01    1   Saturday
5   Rohan     106  46000.0   40            Analysis 2007-12-12   12  Wednesday
6  Suresh     107  32569.0   55             Manager 2016-03-09    9  Wednesday
7    Ravi     108  65897.0   60  frontent-Developer 2019-09-06    6     Friday

In [57]:
df.isnull()

    Name  Emp_id  Payment    Age  Job-Role    DOJ    Day  Day_Name
0  False   False    False  False     False  False  False     False
1  False   False    False  False     False  False  False     False
2  False   False    False  False     False  False  False     False
3  False   False     True  False     False  False  False     False
4  False   False    False  False     False  False  False     False
5  False   False    False  False     False  False  False     False
6  False   False    False  False     False  False  False     False
7  False   False    False  False     False  False  False     False

In [58]:
df.isnull().sum()

Name        0
Emp_id      0
Payment     1
Age         0
Job-Role    0
DOJ         0
Day         0
Day_Name    0
dtype: int64

In [59]:
df.fillna(0)

     Name  Emp_id  Payment  Age            Job-Role        DOJ  Day   Day_Name
0  Ramesh     101  85000.0   25   Backend-Developer 2002-07-13   13   Saturday
1  Suresh     102  69310.0   36              Tester 2026-09-01    1    Tuesday
2    Rahu     103  48612.0   86          Production 2000-09-01    1     Friday
3    Kaju     104      0.0   46           Marketing 1999-04-09    9     Friday
4   Umesh     105  75961.0   30                  HR 2000-01-01    1   Saturday
5   Rohan     106  46000.0   40            Analysis 2007-12-12   12  Wednesday
6  Suresh     107  32569.0   55             Manager 2016-03-09    9  Wednesday
7    Ravi     108  65897.0   60  frontent-Developer 2019-09-06    6     Friday

# 9. Aggregation and group by

In [60]:
df

     Name  Emp_id  Payment  Age            Job-Role        DOJ  Day   Day_Name
0  Ramesh     101  85000.0   25   Backend-Developer 2002-07-13   13   Saturday
1  Suresh     102  69310.0   36              Tester 2026-09-01    1    Tuesday
2    Rahu     103  48612.0   86          Production 2000-09-01    1     Friday
3    Kaju     104      NaN   46           Marketing 1999-04-09    9     Friday
4   Umesh     105  75961.0   30                  HR 2000-01-01    1   Saturday
5   Rohan     106  46000.0   40            Analysis 2007-12-12   12  Wednesday
6  Suresh     107  32569.0   55             Manager 2016-03-09    9  Wednesday
7    Ravi     108  65897.0   60  frontent-Developer 2019-09-06    6     Friday

In [61]:
df['Day_Name'].value_counts()

Day_Name
Friday       3
Saturday     2
Wednesday    2
Tuesday      1
Name: count, dtype: int64

In [62]:
df[df['Day_Name']=='Friday'].value_counts()

Name  Emp_id  Payment  Age  Job-Role            DOJ         Day  Day_Name
Rahu  103     48612.0  86   Production          2000-09-01  1    Friday      1
Ravi  108     65897.0  60   frontent-Developer  2019-09-06  6    Friday      1
Name: count, dtype: int64

In [63]:
df.groupby('Age')['Payment'].sum()

Age
25    85000.0
30    75961.0
36    69310.0
40    46000.0
46        0.0
55    32569.0
60    65897.0
86    48612.0
Name: Payment, dtype: float64

In [64]:
df.groupby('Age')['Payment'].mean()  #Aggregration based on group by

Age
25    85000.0
30    75961.0
36    69310.0
40    46000.0
46        NaN
55    32569.0
60    65897.0
86    48612.0
Name: Payment, dtype: float64

In [65]:
df.groupby('Age').agg({'Payment' : 'mean', 'Name': 'count'})

     Payment  Name
Age
25   85000.0     1
30   75961.0     1
36   69310.0     1
40   46000.0     1
46       NaN     1
55   32569.0     1
60   65897.0     1
86   48612.0     1

# 10. Concatenate and Merge(Join) Data Frame

In [66]:
df1= pd.DataFrame({ 'id' : [5,9,6],
                    'Name' : ['Ayush','Piyush','Ankur'],
                   'age' : [23, 25, 35]})
df1

   id    Name  age
0   5   Ayush   23
1   9  Piyush   25
2   6   Ankur   35

In [67]:
df2= pd.DataFrame({'id' : [5,9,6],
                   'MArks' : [48, 95, 19]})
df2

   id  MArks
0   5     48
1   9     95
2   6     19

In [68]:
pd.concat([df1, df2],axis=0)  #Verticle / row level / top on top

   id    Name   age  MArks
0   5   Ayush  23.0    NaN
1   9  Piyush  25.0    NaN
2   6   Ankur  35.0    NaN
0   5     NaN   NaN   48.0
1   9     NaN   NaN   95.0
2   6     NaN   NaN   19.0

In [69]:
pd.concat([df1, df2],axis=1)   #horizontal / column level / side on side

   id    Name  age  id  MArks
0   5   Ayush   23   5     48
1   9  Piyush   25   9     95
2   6   Ankur   35   6     19

In [70]:
#Join

pd.merge(df1, df2, how='inner', on='id')

   id    Name  age  MArks
0   5   Ayush   23     48
1   9  Piyush   25     95
2   6   Ankur   35     19

In [71]:
pd.merge(df1, df2, how='left', on='id')

   id    Name  age  MArks
0   5   Ayush   23     48
1   9  Piyush   25     95
2   6   Ankur   35     19

In [72]:
pd.merge(df1, df2, how='right', on='id')

   id    Name  age  MArks
0   5   Ayush   23     48
1   9  Piyush   25     95
2   6   Ankur   35     19

In [73]:
pd.merge(df1, df2, how='outer', on='id')

   id    Name  age  MArks
0   5   Ayush   23     48
1   6   Ankur   35     19
2   9  Piyush   25     95