**Q1: Create DataFrame**


```
Create a DataFrame with:
Name: A, B, C
Marks: 80, 90, 85
```

In [1]:
import pandas as pd

In [2]:
df  = pd.DataFrame({'Name' : ['A','B','C'],
                    'Marks': [80,  90, 85]})

df

  Name  Marks
0    A     80
1    B     90
2    C     85

**Q2. Print first 2 rows of DataFrame**

In [3]:
df.head(2)

  Name  Marks
0    A     80
1    B     90

**Q3. Select only "Marks" column**

In [4]:
df[['Marks']]

   Marks
0     80
1     90
2     85

**Q4.  Show students with marks greater than 85**

In [5]:
df[df['Marks']>85]

  Name  Marks
1    B     90


***Q5. Add new column "Grade" based on marks:***
~~~
Marks > 85 → "A"
else → "B"
~~~

In [6]:
df['Grade'] = 'B'
df.loc[df['Marks']>85, 'Grade']='A'
df

  Name  Marks Grade
0    A     80     B
1    B     90     A
2    C     85     B

In [7]:

df['Grade2'] = 'B'
df.loc[df['Marks'] >= 85, 'Grade2']='A'
df

  Name  Marks Grade Grade2
0    A     80     B      B
1    B     90     A      A
2    C     85     B      A

In [8]:
df1 = pd.read_excel(
    "C:/Users/ayush/OneDrive/Desktop/Employee-Management-Sample-Data.xlsx",
    skiprows=5
)
df1

,Unnamed: 0,Employee ID,Full Name,Department,Designation,Hire Date,Annual Salary (USD)
0,NaN,S1001,John Smith,Human Resources,HR Manager,2023-05-15,60000
1,NaN,S1002,Jane Doe,Marketing,Marketing Specialist,2023-08-20,50000
2,NaN,S1003,Michael Johnson,Finance,Financial Analyst,2023-10-10,55000
3,NaN,S1004,Emily Brown,Sales,Sales Representative,2023-03-25,48000
4,NaN,S1005,David Wilson,Information Technology,IT Specialist,2023-09-12,60000
5,NaN,S1006,Lisa Taylor,Operations,Operations Manager,2023-06-30,65000
6,NaN,S1007,Daniel Martinez,Customer Service,Customer Service Representative,2023-11-05,45000
7,NaN,S1008,Sarah Anderson,Research and Development,R&D Engineer,2023-04-18,58000
8,NaN,S1009,Christopher Thomas,Production,Production Supervisor,2023-07-22,52000
9,NaN,S1010,Kimberly Garcia,Quality Assurance,QA Analyst,2023-02-14,56000
10,NaN,S1011,William Hernandez,Human Resources,HR Coordinator,2023-09-01,48000
11,NaN,S1012,Melissa Lopez,Marketing,Marketing Manager,2023-06-10,65000
12,NaN,S1013,Richard Perez,Finance,Finance Manager,2023-11-18,70000
13,NaN,S1014,Jessica Gonzalez,Sales,Sales Manager,2023-05-03,72000
14,NaN,S1015,Matthew Wilson,Information Technology,IT Manager,2023-08-08,75000
15,NaN,S1016,Amanda Martinez,Operations,Operations Coordinator,2023-10-29,48000
16,NaN,S1017,James Johnson,Customer Service,Customer Service Manager,2023-03-12,68000
17,NaN,S1018,Laura Brown,Research and Development,R&D Manager,2023-06-25,70000
18,NaN,S1019,Daniel Smith,Production,Production Manager,2023-09-30,72000
19,NaN,S1020,Jennifer Davis,Quality Assurance,QA Manager,2023-01-17,75000
20,NaN,S1021,Michael Garcia,Human Resources,HR Assistant,2023-07-05,42000
21,NaN,S1022,Amy Hernandez,Marketing,Marketing Coordinator,2023-04-28,48000
22,NaN,S1023,Christopher Rodriguez,Finance,Senior Financial Analyst,2023-11-12,60000
23,NaN,S1024,Jessica Martinez,Sales,Senior Sales Representative,2023-05-25,55000
24,NaN,S1025,David Wilson,Information Technology,Senior IT Specialist,2023-08-30,70000
25,NaN,S1026,Sarah Smith,Operations,Assistant Operations Manager,2023-10-15,55000
26,NaN,S1027,Matthew Johnson,Customer Service,Senior Customer Service Representative,2023-03-28,50000
27,NaN,S1028,Emily Davis,Research and Development,R&D Technician,2023-06-01,48000
28,NaN,S1029,Daniel Wilson,Production,Senior Production Supervisor,2023-09-08,60000
29,NaN,S1030,Jennifer Martinez,Quality Assurance,Senior QA Analyst,2023-02-22,62000
30,NaN,S1031,Michael Smith,Human Resources,HR Generalist,2023-07-17,50000
31,NaN,S1032,Jessica Johnson,Marketing,Marketing Assistant,2023-04-10,42000
32,NaN,S1033,David Brown,Finance,Junior Financial Analyst,2023-11-26,48000
33,NaN,S1034,Sarah Garcia,Sales,Sales Coordinator,2023-06-17,50000
34,NaN,S1035,Matthew Hernandez,Information Technology,Junior IT Specialist,2023-09-20,48000
35,NaN,S1036,Emily Rodriguez,Operations,Operations Assistant,2023-12-03,42000
36,NaN,S1037,Daniel Davis,Customer Service,Customer Service Associate,2023-04-06,40000
37,NaN,S1038,Jennifer Smith,Research and Development,R&D Assistant,2023-07-30,42000
38,NaN,S1039,Michael Johnson,Production,Production Assistant,2023-10-25,40000
39,NaN,S1040,Jessica Martinez,Quality Assurance,QA Assistant,2023-03-20,42000

In [9]:
df1.columns

Index(['Unnamed: 0', 'Employee ID', 'Full Name', 'Department', 'Designation',
       'Hire Date', 'Annual Salary (USD)'],
      dtype='object')

In [10]:
df1.drop('Unnamed: 0', axis = 1, inplace = True)

In [11]:
df1

,Employee ID,Full Name,Department,Designation,Hire Date,Annual Salary (USD)
0,S1001,John Smith,Human Resources,HR Manager,2023-05-15,60000
1,S1002,Jane Doe,Marketing,Marketing Specialist,2023-08-20,50000
2,S1003,Michael Johnson,Finance,Financial Analyst,2023-10-10,55000
3,S1004,Emily Brown,Sales,Sales Representative,2023-03-25,48000
4,S1005,David Wilson,Information Technology,IT Specialist,2023-09-12,60000
5,S1006,Lisa Taylor,Operations,Operations Manager,2023-06-30,65000
6,S1007,Daniel Martinez,Customer Service,Customer Service Representative,2023-11-05,45000
7,S1008,Sarah Anderson,Research and Development,R&D Engineer,2023-04-18,58000
8,S1009,Christopher Thomas,Production,Production Supervisor,2023-07-22,52000
9,S1010,Kimberly Garcia,Quality Assurance,QA Analyst,2023-02-14,56000
10,S1011,William Hernandez,Human Resources,HR Coordinator,2023-09-01,48000
11,S1012,Melissa Lopez,Marketing,Marketing Manager,2023-06-10,65000
12,S1013,Richard Perez,Finance,Finance Manager,2023-11-18,70000
13,S1014,Jessica Gonzalez,Sales,Sales Manager,2023-05-03,72000
14,S1015,Matthew Wilson,Information Technology,IT Manager,2023-08-08,75000
15,S1016,Amanda Martinez,Operations,Operations Coordinator,2023-10-29,48000
16,S1017,James Johnson,Customer Service,Customer Service Manager,2023-03-12,68000
17,S1018,Laura Brown,Research and Development,R&D Manager,2023-06-25,70000
18,S1019,Daniel Smith,Production,Production Manager,2023-09-30,72000
19,S1020,Jennifer Davis,Quality Assurance,QA Manager,2023-01-17,75000
20,S1021,Michael Garcia,Human Resources,HR Assistant,2023-07-05,42000
21,S1022,Amy Hernandez,Marketing,Marketing Coordinator,2023-04-28,48000
22,S1023,Christopher Rodriguez,Finance,Senior Financial Analyst,2023-11-12,60000
23,S1024,Jessica Martinez,Sales,Senior Sales Representative,2023-05-25,55000
24,S1025,David Wilson,Information Technology,Senior IT Specialist,2023-08-30,70000
25,S1026,Sarah Smith,Operations,Assistant Operations Manager,2023-10-15,55000
26,S1027,Matthew Johnson,Customer Service,Senior Customer Service Representative,2023-03-28,50000
27,S1028,Emily Davis,Research and Development,R&D Technician,2023-06-01,48000
28,S1029,Daniel Wilson,Production,Senior Production Supervisor,2023-09-08,60000
29,S1030,Jennifer Martinez,Quality Assurance,Senior QA Analyst,2023-02-22,62000
30,S1031,Michael Smith,Human Resources,HR Generalist,2023-07-17,50000
31,S1032,Jessica Johnson,Marketing,Marketing Assistant,2023-04-10,42000
32,S1033,David Brown,Finance,Junior Financial Analyst,2023-11-26,48000
33,S1034,Sarah Garcia,Sales,Sales Coordinator,2023-06-17,50000
34,S1035,Matthew Hernandez,Information Technology,Junior IT Specialist,2023-09-20,48000
35,S1036,Emily Rodriguez,Operations,Operations Assistant,2023-12-03,42000
36,S1037,Daniel Davis,Customer Service,Customer Service Associate,2023-04-06,40000
37,S1038,Jennifer Smith,Research and Development,R&D Assistant,2023-07-30,42000
38,S1039,Michael Johnson,Production,Production Assistant,2023-10-25,40000
39,S1040,Jessica Martinez,Quality Assurance,QA Assistant,2023-03-20,42000

In [12]:
df1.shape

(40, 6)

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee ID          40 non-null     object
 1   Full Name            40 non-null     object
 2   Department           40 non-null     object
 3   Designation          40 non-null     object
 4   Hire Date            40 non-null     datetime64[ns]
 5   Annual Salary (USD)  40 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 2.0+ KB

In [14]:
df1.describe()

                 Hire Date  Annual Salary (USD)
count                   40            40.000000
mean   2023-07-10 13:12:00         55150.000000
min    2023-01-17 00:00:00         40000.000000
25%    2023-04-25 12:00:00         48000.000000
50%    2023-07-11 00:00:00         53500.000000
75%    2023-09-22 12:00:00         62750.000000
max    2023-12-03 00:00:00         75000.000000
std                    NaN         10654.359888

In [15]:
df1.isnull()

,Employee ID,Full Name,Department,Designation,Hire Date,Annual Salary (USD)
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False

In [16]:
df1.notnull()

,Employee ID,Full Name,Department,Designation,Hire Date,Annual Salary (USD)
0,True,True,True,True,True,True
1,True,True,True,True,True,True
2,True,True,True,True,True,True
3,True,True,True,True,True,True
4,True,True,True,True,True,True
5,True,True,True,True,True,True
6,True,True,True,True,True,True
7,True,True,True,True,True,True
8,True,True,True,True,True,True
9,True,True,True,True,True,True
10,True,True,True,True,True,True
11,True,True,True,True,True,True
12,True,True,True,True,True,True
13,True,True,True,True,True,True
14,True,True,True,True,True,True
15,True,True,True,True,True,True
16,True,True,True,True,True,True
17,True,True,True,True,True,True
18,True,True,True,True,True,True
19,True,True,True,True,True,True
20,True,True,True,True,True,True
21,True,True,True,True,True,True
22,True,True,True,True,True,True
23,True,True,True,True,True,True
24,True,True,True,True,True,True
25,True,True,True,True,True,True
26,True,True,True,True,True,True
27,True,True,True,True,True,True
28,True,True,True,True,True,True
29,True,True,True,True,True,True
30,True,True,True,True,True,True
31,True,True,True,True,True,True
32,True,True,True,True,True,True
33,True,True,True,True,True,True
34,True,True,True,True,True,True
35,True,True,True,True,True,True
36,True,True,True,True,True,True
37,True,True,True,True,True,True
38,True,True,True,True,True,True
39,True,True,True,True,True,True

In [17]:
df1.rename(columns={'Annual Salary (USD)' : 'CTC'}, inplace = True)
df1

,Employee ID,Full Name,Department,Designation,Hire Date,CTC
0,S1001,John Smith,Human Resources,HR Manager,2023-05-15,60000
1,S1002,Jane Doe,Marketing,Marketing Specialist,2023-08-20,50000
2,S1003,Michael Johnson,Finance,Financial Analyst,2023-10-10,55000
3,S1004,Emily Brown,Sales,Sales Representative,2023-03-25,48000
4,S1005,David Wilson,Information Technology,IT Specialist,2023-09-12,60000
5,S1006,Lisa Taylor,Operations,Operations Manager,2023-06-30,65000
6,S1007,Daniel Martinez,Customer Service,Customer Service Representative,2023-11-05,45000
7,S1008,Sarah Anderson,Research and Development,R&D Engineer,2023-04-18,58000
8,S1009,Christopher Thomas,Production,Production Supervisor,2023-07-22,52000
9,S1010,Kimberly Garcia,Quality Assurance,QA Analyst,2023-02-14,56000
10,S1011,William Hernandez,Human Resources,HR Coordinator,2023-09-01,48000
11,S1012,Melissa Lopez,Marketing,Marketing Manager,2023-06-10,65000
12,S1013,Richard Perez,Finance,Finance Manager,2023-11-18,70000
13,S1014,Jessica Gonzalez,Sales,Sales Manager,2023-05-03,72000
14,S1015,Matthew Wilson,Information Technology,IT Manager,2023-08-08,75000
15,S1016,Amanda Martinez,Operations,Operations Coordinator,2023-10-29,48000
16,S1017,James Johnson,Customer Service,Customer Service Manager,2023-03-12,68000
17,S1018,Laura Brown,Research and Development,R&D Manager,2023-06-25,70000
18,S1019,Daniel Smith,Production,Production Manager,2023-09-30,72000
19,S1020,Jennifer Davis,Quality Assurance,QA Manager,2023-01-17,75000
20,S1021,Michael Garcia,Human Resources,HR Assistant,2023-07-05,42000
21,S1022,Amy Hernandez,Marketing,Marketing Coordinator,2023-04-28,48000
22,S1023,Christopher Rodriguez,Finance,Senior Financial Analyst,2023-11-12,60000
23,S1024,Jessica Martinez,Sales,Senior Sales Representative,2023-05-25,55000
24,S1025,David Wilson,Information Technology,Senior IT Specialist,2023-08-30,70000
25,S1026,Sarah Smith,Operations,Assistant Operations Manager,2023-10-15,55000
26,S1027,Matthew Johnson,Customer Service,Senior Customer Service Representative,2023-03-28,50000
27,S1028,Emily Davis,Research and Development,R&D Technician,2023-06-01,48000
28,S1029,Daniel Wilson,Production,Senior Production Supervisor,2023-09-08,60000
29,S1030,Jennifer Martinez,Quality Assurance,Senior QA Analyst,2023-02-22,62000
30,S1031,Michael Smith,Human Resources,HR Generalist,2023-07-17,50000
31,S1032,Jessica Johnson,Marketing,Marketing Assistant,2023-04-10,42000
32,S1033,David Brown,Finance,Junior Financial Analyst,2023-11-26,48000
33,S1034,Sarah Garcia,Sales,Sales Coordinator,2023-06-17,50000
34,S1035,Matthew Hernandez,Information Technology,Junior IT Specialist,2023-09-20,48000
35,S1036,Emily Rodriguez,Operations,Operations Assistant,2023-12-03,42000
36,S1037,Daniel Davis,Customer Service,Customer Service Associate,2023-04-06,40000
37,S1038,Jennifer Smith,Research and Development,R&D Assistant,2023-07-30,42000
38,S1039,Michael Johnson,Production,Production Assistant,2023-10-25,40000
39,S1040,Jessica Martinez,Quality Assurance,QA Assistant,2023-03-20,42000

In [18]:
df1.columns

Index(['Employee ID', 'Full Name', 'Department', 'Designation', 'Hire Date',
       'CTC'],
      dtype='object')

In [19]:
df1.sample()

,Employee ID,Full Name,Department,Designation,Hire Date,CTC
15,S1016,Amanda Martinez,Operations,Operations Coordinator,2023-10-29,48000

In [20]:
df1.sample()

,Employee ID,Full Name,Department,Designation,Hire Date,CTC
30,S1031,Michael Smith,Human Resources,HR Generalist,2023-07-17,50000

In [21]:
df1['CTC'].unique()

array([60000, 50000, 55000, 48000, 65000, 45000, 58000, 52000, 56000,
       70000, 72000, 75000, 68000, 42000, 62000, 40000])

In [22]:
df1['CTC'].value_counts()

CTC
48000    7
42000    5
60000    4
50000    4
55000    3
70000    3
65000    2
72000    2
75000    2
40000    2
45000    1
58000    1
52000    1
56000    1
68000    1
62000    1
Name: count, dtype: int64

In [23]:
df1.groupby('Department')['CTC'].mean()

Department
Customer Service            50750.0
Finance                     58250.0
Human Resources             50000.0
Information Technology      63250.0
Marketing                   51250.0
Operations                  52500.0
Production                  56000.0
Quality Assurance           58750.0
Research and Development    54500.0
Sales                       56250.0
Name: CTC, dtype: float64

In [24]:
df1.groupby('Employee ID')['CTC'].sum()

Employee ID
S1001    60000
S1002    50000
S1003    55000
S1004    48000
S1005    60000
S1006    65000
S1007    45000
S1008    58000
S1009    52000
S1010    56000
S1011    48000
S1012    65000
S1013    70000
S1014    72000
S1015    75000
S1016    48000
S1017    68000
S1018    70000
S1019    72000
S1020    75000
S1021    42000
S1022    48000
S1023    60000
S1024    55000
S1025    70000
S1026    55000
S1027    50000
S1028    48000
S1029    60000
S1030    62000
S1031    50000
S1032    42000
S1033    48000
S1034    50000
S1035    48000
S1036    42000
S1037    40000
S1038    42000
S1039    40000
S1040    42000
Name: CTC, dtype: int64

In [25]:
df1

,Employee ID,Full Name,Department,Designation,Hire Date,CTC
0,S1001,John Smith,Human Resources,HR Manager,2023-05-15,60000
1,S1002,Jane Doe,Marketing,Marketing Specialist,2023-08-20,50000
2,S1003,Michael Johnson,Finance,Financial Analyst,2023-10-10,55000
3,S1004,Emily Brown,Sales,Sales Representative,2023-03-25,48000
4,S1005,David Wilson,Information Technology,IT Specialist,2023-09-12,60000
5,S1006,Lisa Taylor,Operations,Operations Manager,2023-06-30,65000
6,S1007,Daniel Martinez,Customer Service,Customer Service Representative,2023-11-05,45000
7,S1008,Sarah Anderson,Research and Development,R&D Engineer,2023-04-18,58000
8,S1009,Christopher Thomas,Production,Production Supervisor,2023-07-22,52000
9,S1010,Kimberly Garcia,Quality Assurance,QA Analyst,2023-02-14,56000
10,S1011,William Hernandez,Human Resources,HR Coordinator,2023-09-01,48000
11,S1012,Melissa Lopez,Marketing,Marketing Manager,2023-06-10,65000
12,S1013,Richard Perez,Finance,Finance Manager,2023-11-18,70000
13,S1014,Jessica Gonzalez,Sales,Sales Manager,2023-05-03,72000
14,S1015,Matthew Wilson,Information Technology,IT Manager,2023-08-08,75000
15,S1016,Amanda Martinez,Operations,Operations Coordinator,2023-10-29,48000
16,S1017,James Johnson,Customer Service,Customer Service Manager,2023-03-12,68000
17,S1018,Laura Brown,Research and Development,R&D Manager,2023-06-25,70000
18,S1019,Daniel Smith,Production,Production Manager,2023-09-30,72000
19,S1020,Jennifer Davis,Quality Assurance,QA Manager,2023-01-17,75000
20,S1021,Michael Garcia,Human Resources,HR Assistant,2023-07-05,42000
21,S1022,Amy Hernandez,Marketing,Marketing Coordinator,2023-04-28,48000
22,S1023,Christopher Rodriguez,Finance,Senior Financial Analyst,2023-11-12,60000
23,S1024,Jessica Martinez,Sales,Senior Sales Representative,2023-05-25,55000
24,S1025,David Wilson,Information Technology,Senior IT Specialist,2023-08-30,70000
25,S1026,Sarah Smith,Operations,Assistant Operations Manager,2023-10-15,55000
26,S1027,Matthew Johnson,Customer Service,Senior Customer Service Representative,2023-03-28,50000
27,S1028,Emily Davis,Research and Development,R&D Technician,2023-06-01,48000
28,S1029,Daniel Wilson,Production,Senior Production Supervisor,2023-09-08,60000
29,S1030,Jennifer Martinez,Quality Assurance,Senior QA Analyst,2023-02-22,62000
30,S1031,Michael Smith,Human Resources,HR Generalist,2023-07-17,50000
31,S1032,Jessica Johnson,Marketing,Marketing Assistant,2023-04-10,42000
32,S1033,David Brown,Finance,Junior Financial Analyst,2023-11-26,48000
33,S1034,Sarah Garcia,Sales,Sales Coordinator,2023-06-17,50000
34,S1035,Matthew Hernandez,Information Technology,Junior IT Specialist,2023-09-20,48000
35,S1036,Emily Rodriguez,Operations,Operations Assistant,2023-12-03,42000
36,S1037,Daniel Davis,Customer Service,Customer Service Associate,2023-04-06,40000
37,S1038,Jennifer Smith,Research and Development,R&D Assistant,2023-07-30,42000
38,S1039,Michael Johnson,Production,Production Assistant,2023-10-25,40000
39,S1040,Jessica Martinez,Quality Assurance,QA Assistant,2023-03-20,42000

In [26]:
df1[['Full Name']]

                Full Name
0              John Smith
1                Jane Doe
2         Michael Johnson
3             Emily Brown
4            David Wilson
5             Lisa Taylor
6         Daniel Martinez
7          Sarah Anderson
8      Christopher Thomas
9         Kimberly Garcia
10      William Hernandez
11          Melissa Lopez
12          Richard Perez
13       Jessica Gonzalez
14         Matthew Wilson
15        Amanda Martinez
16          James Johnson
17            Laura Brown
18           Daniel Smith
19         Jennifer Davis
20         Michael Garcia
21          Amy Hernandez
22  Christopher Rodriguez
23       Jessica Martinez
24           David Wilson
25            Sarah Smith
26        Matthew Johnson
27            Emily Davis
28          Daniel Wilson
29      Jennifer Martinez
30          Michael Smith
31        Jessica Johnson
32            David Brown
33           Sarah Garcia
34      Matthew Hernandez
35        Emily Rodriguez
36           Daniel Davis
37         Jennifer Smith
38        Michael Johnson
39       Jessica Martinez

In [27]:
df1[df1['CTC']>50000]

,Employee ID,Full Name,Department,Designation,Hire Date,CTC
0,S1001,John Smith,Human Resources,HR Manager,2023-05-15,60000
2,S1003,Michael Johnson,Finance,Financial Analyst,2023-10-10,55000
4,S1005,David Wilson,Information Technology,IT Specialist,2023-09-12,60000
5,S1006,Lisa Taylor,Operations,Operations Manager,2023-06-30,65000
7,S1008,Sarah Anderson,Research and Development,R&D Engineer,2023-04-18,58000
8,S1009,Christopher Thomas,Production,Production Supervisor,2023-07-22,52000
9,S1010,Kimberly Garcia,Quality Assurance,QA Analyst,2023-02-14,56000
11,S1012,Melissa Lopez,Marketing,Marketing Manager,2023-06-10,65000
12,S1013,Richard Perez,Finance,Finance Manager,2023-11-18,70000
13,S1014,Jessica Gonzalez,Sales,Sales Manager,2023-05-03,72000
14,S1015,Matthew Wilson,Information Technology,IT Manager,2023-08-08,75000
16,S1017,James Johnson,Customer Service,Customer Service Manager,2023-03-12,68000
17,S1018,Laura Brown,Research and Development,R&D Manager,2023-06-25,70000
18,S1019,Daniel Smith,Production,Production Manager,2023-09-30,72000
19,S1020,Jennifer Davis,Quality Assurance,QA Manager,2023-01-17,75000
22,S1023,Christopher Rodriguez,Finance,Senior Financial Analyst,2023-11-12,60000
23,S1024,Jessica Martinez,Sales,Senior Sales Representative,2023-05-25,55000
24,S1025,David Wilson,Information Technology,Senior IT Specialist,2023-08-30,70000
25,S1026,Sarah Smith,Operations,Assistant Operations Manager,2023-10-15,55000
28,S1029,Daniel Wilson,Production,Senior Production Supervisor,2023-09-08,60000
29,S1030,Jennifer Martinez,Quality Assurance,Senior QA Analyst,2023-02-22,62000

In [28]:
df1[['Full Name','Department']]

                Full Name                Department
0              John Smith           Human Resources
1                Jane Doe                 Marketing
2         Michael Johnson                   Finance
3             Emily Brown                     Sales
4            David Wilson    Information Technology
5             Lisa Taylor                Operations
6         Daniel Martinez          Customer Service
7          Sarah Anderson  Research and Development
8      Christopher Thomas                Production
9         Kimberly Garcia         Quality Assurance
10      William Hernandez           Human Resources
11          Melissa Lopez                 Marketing
12          Richard Perez                   Finance
13       Jessica Gonzalez                     Sales
14         Matthew Wilson    Information Technology
15        Amanda Martinez                Operations
16          James Johnson          Customer Service
17            Laura Brown  Research and Development
18           Daniel Smith                Production
19         Jennifer Davis         Quality Assurance
20         Michael Garcia           Human Resources
21          Amy Hernandez                 Marketing
22  Christopher Rodriguez                   Finance
23       Jessica Martinez                     Sales
24           David Wilson    Information Technology
25            Sarah Smith                Operations
26        Matthew Johnson          Customer Service
27            Emily Davis  Research and Development
28          Daniel Wilson                Production
29      Jennifer Martinez         Quality Assurance
30          Michael Smith           Human Resources
31        Jessica Johnson                 Marketing
32            David Brown                   Finance
33           Sarah Garcia                     Sales
34      Matthew Hernandez    Information Technology
35        Emily Rodriguez                Operations
36           Daniel Davis          Customer Service
37         Jennifer Smith  Research and Development
38        Michael Johnson                Production
39       Jessica Martinez         Quality Assurance

In [29]:
df1.loc[6,'Full Name']

'Daniel Martinez'

In [30]:
df1.loc[0:2, ['Full Name', 'CTC']]

         Full Name    CTC
0       John Smith  60000
1         Jane Doe  50000
2  Michael Johnson  55000

In [31]:
df2 = {
    'Name': ['Aman', 'Rahul', 'Priya', 'Neha', 'Karan'],
    'Age': [21, 25, 23, 22, 24],
    'Marks': [85, 90, 78, 88, 76]
}

data = pd.DataFrame(df2)

In [32]:
data

    Name  Age  Marks
0   Aman   21     85
1  Rahul   25     90
2  Priya   23     78
3   Neha   22     88
4  Karan   24     76

In [33]:
data.loc[0]

Name     Aman
Age        21
Marks      85
Name: 0, dtype: object

In [34]:
data.iloc[1]

Name     Rahul
Age         25
Marks       90
Name: 1, dtype: object

In [35]:
data.loc[:, ['Name']]

    Name
0   Aman
1  Rahul
2  Priya
3   Neha
4  Karan

In [36]:
data.loc[2, ['Marks']]

Marks    78
Name: 2, dtype: object

In [37]:
data.iloc[3,2]

np.int64(88)

In [38]:
data.loc[data['Age']>22]

    Name  Age  Marks
1  Rahul   25     90
2  Priya   23     78
4  Karan   24     76