In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name' : ['Ayush', 'Ved', 'Ravi', 'Hemant', 'Aryan', 'Ayush', 'Ravi'],
    'Age'  : [24,45,29,30,55, 36, 22],
    'Gmail id' :['ayush@gmail.com', 'ved37@gmail.com', 'ravi98@yahu.com', 'hem@gmail.com', 'aryan56@gmail.com', 'ayushbbu37@gmail.com', 'ravihh67@gmail.com'],
    'Salary':[30000,40000,20000,19500,13500, 6734, 3467]
})
df

     Name  Age              Gmail id  Salary
0   Ayush   24       ayush@gmail.com   30000
1     Ved   45       ved37@gmail.com   40000
2    Ravi   29       ravi98@yahu.com   20000
3  Hemant   30         hem@gmail.com   19500
4   Aryan   55     aryan56@gmail.com   13500
5   Ayush   36  ayushbbu37@gmail.com    6734
6    Ravi   22    ravihh67@gmail.com    3467

In [2]:
df1 = df['Name'].str.upper()
df1

0     AYUSH
1       VED
2      RAVI
3    HEMANT
4     ARYAN
5     AYUSH
6      RAVI
Name: Name, dtype: object

In [3]:
df2 = df['Name'].str.lower()
df2

0     ayush
1       ved
2      ravi
3    hemant
4     aryan
5     ayush
6      ravi
Name: Name, dtype: object

In [4]:
df3 = df[df['Name'].str.startswith('A')]
df3

    Name  Age              Gmail id  Salary
0  Ayush   24       ayush@gmail.com   30000
4  Aryan   55     aryan56@gmail.com   13500
5  Ayush   36  ayushbbu37@gmail.com    6734

In [5]:
df4 = df['Name'].str.replace('Aryan','Neha')
df4

0     Ayush
1       Ved
2      Ravi
3    Hemant
4      Neha
5     Ayush
6      Ravi
Name: Name, dtype: object

In [6]:
df5 = df.copy()

df5[['username', 'domain']] = df['Gmail id'].str.split('@', expand=True)
df5

     Name  Age              Gmail id  Salary    username     domain
0   Ayush   24       ayush@gmail.com   30000       ayush  gmail.com
1     Ved   45       ved37@gmail.com   40000       ved37  gmail.com
2    Ravi   29       ravi98@yahu.com   20000      ravi98   yahu.com
3  Hemant   30         hem@gmail.com   19500         hem  gmail.com
4   Aryan   55     aryan56@gmail.com   13500     aryan56  gmail.com
5   Ayush   36  ayushbbu37@gmail.com    6734  ayushbbu37  gmail.com
6    Ravi   22    ravihh67@gmail.com    3467    ravihh67  gmail.com

In [7]:
df6 = df['Name']+ " Kumar"

df6

0     Ayush Kumar
1       Ved Kumar
2      Ravi Kumar
3    Hemant Kumar
4     Aryan Kumar
5     Ayush Kumar
6      Ravi Kumar
Name: Name, dtype: object

In [8]:
df7 = df['Name'].str.title()
print(df7)

0     Ayush
1       Ved
2      Ravi
3    Hemant
4     Aryan
5     Ayush
6      Ravi
Name: Name, dtype: object

In [9]:
df8 = df['Gmail id'].str.len()
df8

0    15
1    15
2    15
3    13
4    17
5    20
6    18
Name: Gmail id, dtype: int64

In [10]:
df7 = df['Name'].str.strip()
print(df7)

0     Ayush
1       Ved
2      Ravi
3    Hemant
4     Aryan
5     Ayush
6      Ravi
Name: Name, dtype: object

In [11]:
df8 = df['Name'].str.lstrip()
print(df8)

0     Ayush
1       Ved
2      Ravi
3    Hemant
4     Aryan
5     Ayush
6      Ravi
Name: Name, dtype: object

In [12]:
df9 = df['Name'].str.rstrip()
print(df9)

0     Ayush
1       Ved
2      Ravi
3    Hemant
4     Aryan
5     Ayush
6      Ravi
Name: Name, dtype: object

In [13]:
df10 = df['Gmail id'].str.replace("ayushbbu37","pushpendra")
df10

0         ayush@gmail.com
1         ved37@gmail.com
2         ravi98@yahu.com
3           hem@gmail.com
4       aryan56@gmail.com
5    pushpendra@gmail.com
6      ravihh67@gmail.com
Name: Gmail id, dtype: object

In [14]:
df11 = df['Gmail id'].str.split("@")
df11

0         [ayush, gmail.com]
1         [ved37, gmail.com]
2         [ravi98, yahu.com]
3           [hem, gmail.com]
4       [aryan56, gmail.com]
5    [ayushbbu37, gmail.com]
6      [ravihh67, gmail.com]
Name: Gmail id, dtype: object

In [15]:
df12 = df['Gmail id'].str.split("@").str[0]
df12

0         ayush
1         ved37
2        ravi98
3           hem
4       aryan56
5    ayushbbu37
6      ravihh67
Name: Gmail id, dtype: object

In [16]:
df13 = df[df['Name'].str.endswith('i')]
df13

   Name  Age            Gmail id  Salary
2  Ravi   29     ravi98@yahu.com   20000
6  Ravi   22  ravihh67@gmail.com    3467

In [17]:
df14 = df['Name'].str.contains('a')
df14

0    False
1    False
2     True
3     True
4     True
5    False
6     True
Name: Name, dtype: bool

In [18]:
df15 = df['Name'].str.count('a')
df15

0    0
1    0
2    1
3    1
4    1
5    0
6    1
Name: Name, dtype: int64

In [19]:
df16 = df['Name'].str[:3]
df16

0    Ayu
1    Ved
2    Rav
3    Hem
4    Ary
5    Ayu
6    Rav
Name: Name, dtype: object